### ISSUE TITLE
can't train model because ph_seq is set to None

### ISSUE THREAD

**Issue by vocatart** [qiuqiao/SOFA#21]
I don't know enough about python to be able to fix this problem with a pr, so I hope this is descriptive enough

commit 7cd5771 adds `wav_length` to `_infer_once`, but doesn't change arguments provided in `validation_step`
https://github.com/qiuqiao/SOFA/blob/7cd57710a31b7d7b9ca760adaa8fa2dc6c9ff15e/modules/task/forced_alignment.py#L774-L781
this sets `ph_seq` to None, causing `_infer_once` to fail with a NoneType error when using train.py. I reverted back to commit 2591e98 and this error was resolved.

**Comment by qiuqiao** [comment]
I'm sorry for submitting the commit without adequate testing. I will be more careful in the future.

**Comment by vocatart** [comment]
don't worry about it! I'm really happy with the results I'm getting with SOFA so far! keep up the good work :)
