### ISSUE TITLE
Please help. I encountered an error when trying to execute python binarize.py before training.

### ISSUE THREAD

**Issue by Oliver0621** [qiuqiao/SOFA#23]
![image](https://github.com/qiuqiao/SOFA/assets/137243056/3a7ebc0c-9bc7-4a82-8166-0c5c642ea59a)

My steps are to refer to this
https://github.com/MLo7Ghinsan/DiffSinger_colab_notebook_MLo7/blob/main/SOFA_Notebook.ipynb

But I just use the previous installation dependency code and dependency part.I'm not using the **Extract Data** part of the code. Because I have split the wav file locally.

Then I put the split wav file and transcriptions.csv file in the data directory.
![image](https://github.com/qiuqiao/SOFA/assets/137243056/5b8f9d2d-37ac-4180-a0a3-bce51e26895c)

Then I executed the code below. Then I encountered the above error.
`
%cd /content/SOFA

if not os.path.exists("data/binary/global_config.yaml"):
    os.makedirs("data/binary")
    with open("data/binary/global_config.yaml", "w") as file:
        pass

!source activate aligner; \
python binarize.py

`

**Comment by qiuqiao** [comment]
How many .wav audio files do you have? Or, how many rows are there in the transcriptions.csv file? It seems that the error is due to having too little data. By default, the valid_set_size is 15, which means at least fifteen audio files are needed to have sufficient data for training.

**Comment by Oliver0621** [comment]
wow, okay, mine only has 11 audio files. Thank you. I'll add more data and try again.

**Comment by Oliver0621** [comment]
The above error is caused by the fact that I only added full_label and did not add weak_label and no_label data. After I added it, it worked normally.
