### ISSUE TITLE
Which ckpt should be chosen? What parameters need to be comprehensively considered?

### ISSUE THREAD

**Issue by Oliver0621** [qiuqiao/SOFA#25]
![image](https://github.com/qiuqiao/SOFA/assets/137243056/3542cc6c-56f1-4d0c-b69d-2cb2be794aaf)

**Comment by Oliver0621** [comment]
I always use the last ckpt after training for 100,000 steps. I wonder if this is the best one?

**Comment by qiuqiao** [comment]
Yes, the last ckpt is generally the best one. In future versions, SOFA will provide metrics that better reflect model performance, but for now, the last checkpoint is typically the best option.
